#ifndef _DR2_H
#define _DR2_H

//Fields taken from https://gist.github.com/lucasw/5350f5f96f7b2302e155dd31c42faaf4
// Also see https://gea.esac.esa.int/archive/documentation/GDR2/Gaia_archive/chap_datamodel/sec_dm_main_tables/ssec_dm_gaia_source.html 
// Distance parsecs = 1.0 / (parallax / 1000.0)
enum dr2fields
{
	dr2_solution_id = 0,
	dr2_designation,
	dr2_source_id,
	dr2_random_index,
	dr2_ref_epoch,
	dr2_ra,
	dr2_ra_error,
	dr2_dec,
	dr2_dec_error,
	dr2_parallax,
	dr2_parallax_error,
	dr2_parallax_over_error,
	dr2_pmra,
	dr2_pmra_error,
	dr2_pmdec,
	dr2_pmdec_error,
	dr2_ra_dec_corr,
	dr2_ra_parallax_corr,
	dr2_ra_pmra_corr,
	dr2_ra_pmdec_corr,
	dr2_dec_parallax_corr,
	dr2_dec_pmra_corr,
	dr2_dec_pmdec_corr,
	dr2_parallax_pmra_corr,
	dr2_parallax_pmdec_corr,
	dr2_pmra_pmdec_corr,
	dr2_astrometric_n_obs_al,
	dr2_astrometric_n_obs_ac,
	dr2_astrometric_n_good_obs_al,
	dr2_astrometric_n_bad_obs_al,
	dr2_astrometric_gof_al,
	dr2_astrometric_chi2_al,
	dr2_astrometric_excess_noise,
	dr2_astrometric_excess_noise_sig,
	dr2_astrometric_params_solved,
	dr2_astrometric_primary_flag,
	dr2_astrometric_weight_al,
	dr2_astrometric_pseudo_colour,
	dr2_astrometric_pseudo_colour_error,
	dr2_mean_varpi_factor_al,
	dr2_astrometric_matched_observations,
	dr2_visibility_periods_used,
	dr2_astrometric_sigma5d_max,
	dr2_frame_rotator_object_type,
	dr2_matched_observations,
	dr2_duplicated_source,
	dr2_phot_g_n_obs,
	dr2_phot_g_mean_flux,
	dr2_phot_g_mean_flux_error,
	dr2_phot_g_mean_flux_over_error,
	dr2_phot_g_mean_mag,
	dr2_phot_bp_n_obs,
	dr2_phot_bp_mean_flux,
	dr2_phot_bp_mean_flux_error,
	dr2_phot_bp_mean_flux_over_error,
	dr2_phot_bp_mean_mag,
	dr2_phot_rp_n_obs,
	dr2_phot_rp_mean_flux,
	dr2_phot_rp_mean_flux_error,
	dr2_phot_rp_mean_flux_over_error,
	dr2_phot_rp_mean_mag,
	dr2_phot_bp_rp_excess_factor,
	dr2_phot_proc_mode,
	dr2_bp_rp,
	dr2_bp_g,
	dr2_g_rp,
	dr2_radial_velocity,
	dr2_radial_velocity_error,
	dr2_rv_nb_transits,
	dr2_rv_template_teff,
	dr2_rv_template_logg,
	dr2_rv_template_fe_h,
	dr2_phot_variable_flag,
	dr2_l,
	dr2_b,
	dr2_ecl_lon,
	dr2_ecl_lat,
	dr2_priam_flags,
	dr2_teff_val,
	dr2_teff_percentile_lower,
	dr2_teff_percentile_upper,
	dr2_a_g_val,
	dr2_a_g_percentile_lower,
	dr2_a_g_percentile_upper,
	dr2_e_bp_min_rp_val,
	dr2_e_bp_min_rp_percentile_lower,
	dr2_e_bp_min_rp_percentile_upper,
	dr2_flame_flags,
	dr2_radius_val,
	dr2_radius_percentile_lower,
	dr2_radius_percentile_upper,
	dr2_lum_val,
	dr2_lum_percentile_lower,
	dr2_lum_percentile_upper
};

#endif

